language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.0
gemfile:
  - gemfiles/sprockets_2.gemfile
  - gemfiles/sprockets_3.gemfile
  - gemfiles/sprockets_4.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/therubyracer.gemfile

matrix:
  exclude:
  - rvm: 2.0
    gemfile: gemfiles/sprockets_3.gemfile
  - rvm: 2.0
    gemfile: gemfiles/sprockets_4.gemfile
  - rvm: 2.0
    gemfile: gemfiles/therubyracer.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_5.1.gemfile
