language: ruby
rvm:
  - 2.6
gemfile:
  - gemfiles/sprockets_2.gemfile
  - gemfiles/sprockets_3.gemfile
  - gemfiles/sprockets_4.gemfile
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/rails_3.gemfile
    - gemfile: gemfiles/rails_4.gemfile
  include:
    - rvm: 2.0
      gemfile: gemfiles/sprockets_2.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_4.gemfile

    - rvm: 2.6
      install:
      script: "bundle exec rubocop"
      env: "RUBOCOP=true"